version: '3.8'

services:
  php:
    image: php:8.2-fpm
    container_name: symfony_php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: postgres:15
    container_name: symfony_postgres
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"